In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  #создаем двумерный массив из списков
b = np.eye(3)  #создаем единичную матрицу

print(a.dtype)  #тип данных
print(a.shape)  #форма массива

print(a[1][2])  #отдельный элемент из массива (2 строчка 3 элемент)
print(a[2][:2])  #извлечение подмассива (3 строчка первые 2 элемента)

print(a + b)  #поэлементное сложение матриц a и b
print(a.max(axis=1))  #максимальный элемент из каждой строки
print(a.mean())  #среднее арифметическое


int64
(3, 3)
6
[7 8]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[3 6 9]
5.0
