In [16]:
import numpy as np

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  #создаем двумерный массив из списков

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
b = np.eye(3)  #создаем единичную матрицу

In [20]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
a.dtype  #тип данных

dtype('int64')

In [22]:
a.shape  #форма массива

(3, 3)

In [23]:
a[1][2]  ##отдельный элемент из массива (2 строчка 3 элемент)

np.int64(6)

In [24]:
a[2][:2]  #извлечение подмассива (3 строчка первые 2 элемента)

array([7, 8])

In [25]:
a + b  #поэлементное сложение матриц a и b

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [26]:
a.max(axis=1)  #максимальный элемент из каждой строки

array([3, 6, 9])

In [27]:
a.mean()  #среднее арифметическое

np.float64(5.0)